/**
 * Content Integrity Checker
 * 
 * RULE: Every line of tailored output MUST exist verbatim in the source input.
 * The tailoring engine may ONLY reorder lines and sections — never add, modify,
 * or fabricate content. This checker is the enforcement gate.
 * 
 * Two-layer verification:
 * 1. LINE-MEMBERSHIP CHECK (primary gate): every non-empty output line must
 *    exist as a line in the input. This is the hard block.
 * 2. CLAIM EXTRACTION CHECK (secondary): regex-based extraction of factual
 *    claims (numbers, %, tool names) — provides friendlier violation messages.
 */

/**
 * Normalize a line for comparison — trims whitespace, collapses internal
 * whitespace, lowercases. Section header labels generated by the formatter
 * (e.g., "PROFESSIONAL SUMMARY") are allowed through.
 */
function normalizeLine(line) {
  return line.trim().replace(/\s+/g, ' ').toLowerCase();
}

// Section headers that the resume formatter is allowed to generate
const ALLOWED_GENERATED_LINES = new Set([
  'professional summary',
  'technical skills',
  'professional experience',
  'projects',
  'education',
  'certifications',
  'awards & achievements',
  'publications',
  'volunteer experience',
  'languages',
  'interests',
]);

/**
 * Check if a line is a formatting artifact (separator, header, empty)
 * that the generator is permitted to produce.
 */
function isFormattingLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return true;
  // Box-drawing / separator lines
  if (/^[─━═\-_~]{3,}$/.test(trimmed)) return true;
  // Check against allowed generated section headers
  if (ALLOWED_GENERATED_LINES.has(trimmed.toLowerCase())) return true;
  return false;
}

/**
 * PRIMARY GATE: Line-membership check.
 * Every non-formatting line in the output must exist verbatim (after
 * normalization) in the source input.
 * 
 * @param {string} sourceText - The original resume text the user provided
 * @param {string} tailoredText - The generated tailored resume text
 * @returns {{ passed: boolean, violations: string[] }}
 */
export function checkLineMembership(sourceText, tailoredText) {
  // Build a set of all normalized source lines
  const sourceLines = new Set(
    sourceText.split('\n').map(normalizeLine).filter(Boolean)
  );

  const outputLines = tailoredText.split('\n');
  const violations = [];

  for (let i = 0; i < outputLines.length; i++) {
    const line = outputLines[i];
    if (isFormattingLine(line)) continue;

    const normalized = normalizeLine(line);
    if (!normalized) continue;

    if (!sourceLines.has(normalized)) {
      // Check if the line is a comma-reordered skill list
      // Skills like "React, Node, Docker" might get reordered to "Docker, React, Node"
      // — same items, different order. This is allowed.
      if (isReorderedList(normalized, sourceLines)) continue;

      violations.push({
        line: i + 1,
        content: line.trim(),
        reason: 'This line does not appear in your original resume',
      });
    }
  }

  return {
    passed: violations.length === 0,
    violations,
    summary: violations.length === 0
      ? '✅ All content verified — nothing was added or fabricated'
      : `⚠️ ${violations.length} line(s) in the output could not be traced back to your original resume`,
  };
}

/**
 * Check if a line is a reordered comma-separated list whose items all
 * exist in the source. E.g., "React, Docker, Node" reordered from
 * "Node, React, Docker" — same items, different order.
 */
function isReorderedList(normalizedLine, sourceLines) {
  // Only applies to comma-separated lines
  if (!normalizedLine.includes(',')) return false;

  const outputItems = new Set(
    normalizedLine.split(',').map(s => s.trim().toLowerCase()).filter(Boolean)
  );

  if (outputItems.size < 2) return false;

  // Check if there's a source line whose items are a superset of the output items
  for (const sourceLine of sourceLines) {
    if (!sourceLine.includes(',')) continue;

    const sourceItems = new Set(
      sourceLine.split(',').map(s => s.trim().toLowerCase()).filter(Boolean)
    );

    // All output items must exist in this source line
    let allFound = true;
    for (const item of outputItems) {
      if (!sourceItems.has(item)) {
        allFound = false;
        break;
      }
    }

    if (allFound) return true;
  }

  return false;
}

/**
 * SECONDARY CHECK: Extract factual claims from the output and verify
 * each one exists in the source. Provides friendlier violation messages.
 * 
 * Factual claims = numbers with %, dollar amounts, X+ counts, tool/tech names
 * that appear in skill dictionaries.
 */
export function checkFactualClaims(sourceText, tailoredText) {
  const sourceLower = sourceText.toLowerCase();
  const claims = [];

  // Extract percentage claims
  const percentages = tailoredText.match(/\d+(\.\d+)?%/g) || [];
  for (const pct of percentages) {
    if (!sourceLower.includes(pct.toLowerCase())) {
      claims.push({ claim: pct, type: 'metric', reason: `"${pct}" not found in your original resume` });
    }
  }

  // Extract dollar amounts
  const dollars = tailoredText.match(/\$[\d,]+(\.\d+)?/g) || [];
  for (const d of dollars) {
    if (!sourceLower.includes(d.toLowerCase())) {
      claims.push({ claim: d, type: 'metric', reason: `"${d}" not found in your original resume` });
    }
  }

  // Extract "X+ users/projects/etc" claims
  const plusClaims = tailoredText.match(/\d+\+?\s*(?:users|customers|clients|projects|team\s+members|engineers|developers|applications|services|microservices)/gi) || [];
  for (const pc of plusClaims) {
    if (!sourceLower.includes(pc.toLowerCase())) {
      claims.push({ claim: pc, type: 'metric', reason: `"${pc}" not found in your original resume` });
    }
  }

  return {
    passed: claims.length === 0,
    claims,
    summary: claims.length === 0
      ? '✅ All factual claims verified against source'
      : `⚠️ ${claims.length} factual claim(s) could not be verified`,
  };
}

/**
 * Run full integrity verification — both checks.
 * The line-membership check is the hard gate.
 */
export function verifyIntegrity(sourceText, tailoredText) {
  const lineCheck = checkLineMembership(sourceText, tailoredText);
  const claimCheck = checkFactualClaims(sourceText, tailoredText);

  return {
    passed: lineCheck.passed, // Line membership is the hard gate
    lineCheck,
    claimCheck,
    summary: lineCheck.passed
      ? '✅ Integrity verified — output contains only your original content, reordered'
      : `🚫 Integrity check failed — ${lineCheck.violations.length} line(s) may contain fabricated content`,
  };
}
