// Comprehensive English stop words list for filtering
export const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'be',
  'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
  'would', 'could', 'should', 'may', 'might', 'shall', 'can', 'need',
  'dare', 'ought', 'used', 'it', 'its', 'this', 'that', 'these', 'those',
  'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
  'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself',
  'she', 'her', 'hers', 'herself', 'they', 'them', 'their', 'theirs',
  'themselves', 'what', 'which', 'who', 'whom', 'when', 'where', 'why',
  'how', 'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other',
  'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so',
  'than', 'too', 'very', 'just', 'because', 'if', 'then', 'also',
  'about', 'up', 'out', 'off', 'over', 'under', 'again', 'further',
  'once', 'here', 'there', 'any', 'into', 'through', 'during', 'before',
  'after', 'above', 'below', 'between', 'while', 'etc', 'eg', 'ie',
  'able', 'across', 'along', 'already', 'although', 'among', 'another',
  'around', 'away', 'back', 'become', 'becomes', 'becoming', 'behind',
  'besides', 'beyond', 'bring', 'brought', 'came', 'come', 'comes',
  'coming', 'done', 'down', 'either', 'else', 'enough', 'even', 'ever',
  'get', 'gets', 'getting', 'give', 'given', 'gives', 'go', 'goes',
  'going', 'gone', 'got', 'gotten', 'hence', 'however', 'indeed',
  'keep', 'keeps', 'kept', 'know', 'known', 'knows', 'last', 'later',
  'least', 'less', 'let', 'like', 'likely', 'long', 'look', 'looking',
  'looks', 'made', 'make', 'makes', 'making', 'many', 'maybe', 'might',
  'much', 'must', 'neither', 'never', 'new', 'next', 'nobody', 'none',
  'nothing', 'now', 'often', 'per', 'perhaps', 'please', 'put', 'quite',
  'rather', 'really', 'regarding', 'right', 'said', 'say', 'says',
  'see', 'seem', 'seemed', 'seeming', 'seems', 'several', 'since',
  'still', 'take', 'taken', 'takes', 'taking', 'tell', 'tends', 'thing',
  'things', 'think', 'thinking', 'though', 'throughout', 'thus', 'till',
  'together', 'toward', 'towards', 'try', 'trying', 'upon', 'us',
  'use', 'using', 'usually', 'want', 'wants', 'way', 'ways', 'well',
  'went', 'what', 'whatever', 'whenever', 'whether', 'within', 'without',
  'work', 'working', 'works', 'yet',
  // Job posting filler words
  'responsibilities', 'responsibility', 'required', 'requirements',
  'qualifications', 'preferred', 'description', 'position', 'role',
  'company', 'team', 'candidate', 'candidates', 'experience',
  'opportunity', 'join', 'looking', 'seeking', 'ideal', 'including',
  'includes', 'include', 'based', 'related', 'relevant', 'strong',
  'excellent', 'good', 'great', 'best', 'years', 'year', 'day', 'days',
  'week', 'month', 'time', 'full', 'part', 'plus', 'bonus', 'salary',
  'compensation', 'benefits', 'benefit', 'equal', 'employer',
  'employment', 'status', 'apply', 'application', 'submit', 'deadline',
  'location', 'remote', 'hybrid', 'onsite', 'office',
]);

// Words that should NOT be filtered even if they seem common in job context
export const KEEP_WORDS = new Set([
  'api', 'ui', 'ux', 'qa', 'ci', 'cd', 'ml', 'ai', 'db', 'os', 'io',
  'rest', 'soap', 'crud', 'mvc', 'orm', 'cli', 'sdk', 'ide', 'ssl',
  'ssh', 'dns', 'tcp', 'http', 'https', 'html', 'css', 'sql', 'nosql',
  'xml', 'json', 'yaml', 'csv', 'pdf', 'svg',
  'agile', 'scrum', 'kanban', 'devops', 'devsecops',
  'lead', 'senior', 'junior', 'principal', 'staff', 'architect',
  'manager', 'director', 'engineer', 'developer', 'analyst',
  'design', 'develop', 'build', 'test', 'deploy', 'maintain',
  'optimize', 'scale', 'automate', 'integrate', 'implement',
  'collaborate', 'mentor', 'review', 'debug', 'troubleshoot',
]);
