// Comprehensive English stop words list for filtering
export const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'be',
  'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
  'would', 'could', 'should', 'may', 'might', 'shall', 'can', 'need',
  'dare', 'ought', 'used', 'it', 'its', 'this', 'that', 'these', 'those',
  'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
  'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself',
  'she', 'her', 'hers', 'herself', 'they', 'them', 'their', 'theirs',
  'themselves', 'what', 'which', 'who', 'whom', 'when', 'where', 'why',
  'how', 'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other',
  'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so',
  'than', 'too', 'very', 'just', 'because', 'if', 'then', 'also',
  'about', 'up', 'out', 'off', 'over', 'under', 'again', 'further',
  'once', 'here', 'there', 'any', 'into', 'through', 'during', 'before',
  'after', 'above', 'below', 'between', 'while', 'etc', 'eg', 'ie',
  'able', 'across', 'along', 'already', 'although', 'among', 'another',
  'around', 'away', 'back', 'become', 'becomes', 'becoming', 'behind',
  'besides', 'beyond', 'bring', 'brought', 'came', 'come', 'comes',
  'coming', 'done', 'down', 'either', 'else', 'enough', 'even', 'ever',
  'get', 'gets', 'getting', 'give', 'given', 'gives', 'go', 'goes',
  'going', 'gone', 'got', 'gotten', 'hence', 'however', 'indeed',
  'keep', 'keeps', 'kept', 'know', 'known', 'knows', 'last', 'later',
  'least', 'less', 'let', 'like', 'likely', 'long', 'look', 'looking',
  'looks', 'made', 'make', 'makes', 'making', 'many', 'maybe', 'might',
  'much', 'must', 'neither', 'never', 'new', 'next', 'nobody', 'none',
  'nothing', 'now', 'often', 'per', 'perhaps', 'please', 'put', 'quite',
  'rather', 'really', 'regarding', 'right', 'said', 'say', 'says',
  'see', 'seem', 'seemed', 'seeming', 'seems', 'several', 'since',
  'still', 'take', 'taken', 'takes', 'taking', 'tell', 'tends', 'thing',
  'things', 'think', 'thinking', 'though', 'throughout', 'thus', 'till',
  'together', 'toward', 'towards', 'try', 'trying', 'upon', 'us',
  'use', 'using', 'usually', 'want', 'wants', 'way', 'ways', 'well',
  'went', 'what', 'whatever', 'whenever', 'whether', 'within', 'without',
  'work', 'working', 'works', 'yet',

  // Job posting filler words
  'responsibilities', 'responsibility', 'required', 'requirements',
  'qualifications', 'preferred', 'description', 'position', 'role',
  'company', 'team', 'candidate', 'candidates', 'experience',
  'opportunity', 'join', 'looking', 'seeking', 'ideal', 'including',
  'includes', 'include', 'based', 'related', 'relevant', 'strong',
  'excellent', 'good', 'great', 'best', 'years', 'year', 'day', 'days',
  'week', 'month', 'time', 'full', 'part', 'plus', 'bonus', 'salary',
  'compensation', 'benefits', 'benefit', 'equal', 'employer',
  'employment', 'status', 'apply', 'application', 'submit', 'deadline',
  'location', 'remote', 'hybrid', 'onsite', 'office',

  // Generic English vocabulary that JDs use but are NOT resume skills
  'job', 'innovations',
  'experienced', 'play', 'crucial', 'someone', 'thrives', 'thrive',
  'environment', 'deep', 'modern',
  'rich', 'external', 'partners', 'partner', 'specifically',
  'utilizing', 'utilize', 'thorough', 'thoroughly',
  'ensure', 'ensures', 'ensuring', 'stability',
  'stable', 'sessions', 'session', 'expertise', 'proven',
  'hands-on', 'strategies', 'strategy', 'grasp',
  'ability', 'abilities', 'independently', 'independent', 'nice',
  'familiarity', 'familiar', 'contributions', 'contribute',
  'contributing', 'contribution', 'background', 'backgrounds',
  'knowledge', 'proficiency', 'proficient',
  'comfortable', 'passionate', 'passion', 'driven', 'dynamic',
  'fast-paced', 'world-class', 'cutting-edge', 'state-of-the-art',
  'next-generation', 'high-performance', 'mission-critical',
  'end', 'cross', 'functional',

  // More generic JD filler
  'deliver', 'delivering', 'deliverables', 'stakeholders', 'stakeholder',
  'collaborate', 'collaborating', 'collaboration', 'collaborative',
  'effectively', 'effective', 'efficient', 'efficiently',
  'responsible', 'focus', 'focused', 'focusing',
  'solutions', 'solution', 'solve', 'solving',
  'identify', 'identifying', 'identified',
  'develop', 'developing', 'development',
  'create', 'creating', 'creation',
  'support', 'supporting', 'supported',
  'improve', 'improving', 'improvement', 'improvements',
  'build', 'building', 'built',
  'provide', 'providing', 'provided',
  'manage', 'managing', 'managed',
  'define', 'defining', 'defined',
  'review', 'reviewing', 'reviewed',
  'perform', 'performing', 'performed',
  'participate', 'participating',
  'communicate', 'communicating',
  'coordinate', 'coordinating',
  'assist', 'assisting',
  'report', 'reporting', 'reports',
  'track', 'tracking',
  'handle', 'handling',
  'follow', 'following',
  'learn', 'learning',
  'grow', 'growing', 'growth',
  'achieve', 'achieving',
  'meet', 'meeting', 'meetings',
  'plan', 'planning', 'planned',
  'prepare', 'preparing',
  'process', 'processes', 'processing',
  'implement', 'implementing', 'implementation',
  'establish', 'establishing', 'established',
  'evaluate', 'evaluating', 'evaluation',
  'monitor', 'monitoring',
  'resolve', 'resolving',
  'conduct', 'conducting',
  'oversee', 'overseeing',
  'execute', 'executing', 'execution',
  'analyze', 'analyzing', 'analysis',
  'assess', 'assessing', 'assessment',
  'research', 'researching',
  'document', 'documenting', 'documentation',
  'update', 'updating',
  'complete', 'completing', 'completion',
  'demonstrate', 'demonstrating', 'demonstrated',
  'contribute', 'contributing',
  'operate', 'operating',
  'interact', 'interacting', 'interaction',
  'respond', 'responding',
  'address', 'addressing',
  'apply', 'applying', 'applied',
  'offer', 'offering', 'offers',
  'represent', 'representing',
  'share', 'sharing',
  'protect', 'protecting',
  'promote', 'promoting',
  'organize', 'organizing',
]);

// Words that should NOT be filtered even if they seem common in job context
export const KEEP_WORDS = new Set([
  'api', 'ui', 'ux', 'qa', 'ci', 'cd', 'ml', 'ai', 'db', 'os', 'io',
  'rest', 'soap', 'crud', 'mvc', 'orm', 'cli', 'sdk', 'ide', 'ssl',
  'ssh', 'dns', 'tcp', 'http', 'https', 'html', 'css', 'sql', 'nosql',
  'xml', 'json', 'yaml', 'csv', 'pdf', 'svg',
  'agile', 'scrum', 'kanban', 'devops', 'devsecops',
  'architect', 'engineer', 'developer', 'analyst',
  'design', 'test', 'deploy',
  'optimize', 'scale', 'automate', 'integrate',
  'debug', 'troubleshoot',
  'lead', 'senior', 'junior', 'mentor', 'maintain',
  'interfaces', 'architectural', 'services', 'patterns',
  'management', 'unit', 'tests', 'testing', 'end-to-end',
  'write', 'writing', 'understanding',
]);
